services:
  backend:
    image: dockiq-backend:latest
    ports:
      - '3007:3007' # Map backend's internal port 3007 to host's port 3007
    environment:
      NODE_ENV: production
      PORT: 3007 # Match this with the port in app.ts
      PROMETHEUS_URL: http://prometheus:9090
      GRAFANA_URL: http://grafana:3000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - prometheus
      - grafana

  frontend:
    image: dockiq-frontend:latest
    ports:
      - '3001:3000' # Map frontend's internal port 3000 to host's port 3001
    environment:
      NODE_ENV: production
      BACKEND_URL: http://backend:3007 # Match this with the backend service port
    depends_on:
      - backend

  prometheus:
    image: dockiq-prometheus:latest
    ports:
      - '9094:9090' # Map Prometheus's internal port 9090 to host's port 9094

  grafana:
    image: grafana/grafana
    ports:
      - '3006:3000' # Map Grafana's internal port 3000 to host's port 3006
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    volumes:
      - grafana-data:/var/lib/grafana

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    ports:
      - '8084:8080' # Map cAdvisor's internal port 8080 to host's port 8084
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    privileged: true

volumes:
  grafana-data: # Declare the named volume here
