version: '3.8'
# The services section defines individual containers that will run in this environment. Each service has its own configuration
services:
  prometheus:
    image: prom/prometheus
    ports:
      - '9090:9090'
    # A volume mount maps a file or directory on our local machine (host) to a path inside the Docker container
    # Mounts the prometheus.yml file from our local machine into the container specified below. This file tells Prometheus which metrics to scrape (e.g., from cAdvisor)
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    ports:
      - '3100:3000'

  cadvisor:
    image: gcr.io/cadvisor/cadvisor
    ports:
      - '8180:8080'
    volumes:
      # Mounts critical system directories into the container so cAdvisor can monitor resource usage
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
