version: '3.9'
services:
  backend:
    image: dockiq-backend:latest
    ports:
      - '3003:3000'
    environment:
      NODE_ENV: production
      PORT: 3000
      PROMETHEUS_URL: http://prometheus:9090
      GRAFANA_URL: http://grafana:3100
    depends_on:
      - prometheus
      - grafana

  frontend:
    image: dockiq-frontend:latest
    ports:
      - '3102:80'
    environment:
      NODE_ENV: production
      BACKEND_URL: http://backend:3000
    depends_on:
      - backend

  prometheus:
    image: dockiq-prometheus:latest # Use your custom Prometheus image
    ports:
      - '9092:9090' # Custom external port mapped to Prometheus internal port
    # Volume is no longer needed since the configuration is baked into the image

  grafana:
    image: grafana/grafana
    ports:
      - '3106:3000'
    environment:
      GF_SECURITY_ADMIN_USER: kimalena9
      GF_SECURITY_ADMIN_PASSWORD: fartpoopieapple
    volumes:
      - grafana-data:/var/lib/grafana

volumes:
  grafana-data:
