services:
  backend:
    image: dockiq-backend:latest
    ports:
      - '3003:3003'
    environment:
      NODE_ENV: production
      PORT: 3003
      PROMETHEUS_URL: http://prometheus:9090
      GRAFANA_URL: http://grafana:3000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - prometheus
      - grafana
    networks:
      - dockiq-network

  frontend:
    image: dockiq-frontend:latest
    ports:
      - '3001:3000'
    environment:
      NODE_ENV: production
      BACKEND_URL: http://backend:3003
    depends_on:
      - backend
    networks:
      - dockiq-network

  prometheus:
    image: dockiq-prometheus:latest
    ports:
      - '9094:9090'
    volumes:
      - prometheus-data:/prometheus
    networks:
      - dockiq-network

  grafana:
    image: grafana/grafana
    ports:
      - '3006:3000'
    volumes:
      - grafana-data:/var/lib/grafana
    environment:
      - GF_SERVER_ROOT_URL=http://localhost:3006
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Viewer
      - GF_SECURITY_ALLOW_EMBEDDING=true
      - GF_FEATURE_TOGGLES_PUBLIC_DASHBOARDS=true
    networks:
      - dockiq-network

volumes:
  grafana-data:
    external: true
  prometheus-data:
    external: true

networks:
  dockiq-network:
    driver: bridge
