services:
  backend:
    image: dockiq-backend:latest
    ports:
      - '3003:3003' # Map backend's internal port 3000 to host's port 3001
    environment:
      NODE_ENV: production
      PORT: 3003
      PROMETHEUS_URL: http://prometheus:9090
      GRAFANA_URL: http://grafana:3000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - prometheus
      - grafana

  frontend:
    image: dockiq-frontend:latest
    ports:
      - '3001:3000' # Frontend stays on host port 3000
    environment:
      NODE_ENV: production
      BACKEND_URL: http://backend:3000
    depends_on:
      - backend

  prometheus:
    image: dockiq-prometheus:latest
    ports:
      - '9094:9090' # Map Prometheus's internal port 9090 to host's port 9090

  grafana:
    image: grafana/grafana
    ports:
      - '3006:3000' # Map Grafana's internal port 3000 to host's port 3002
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    volumes:
      - grafana-data:/var/lib/grafana

volumes:
  grafana-data: # Declare the named volume here
