global:
  scrape_interval: 5s
  scrape_timeout: 10s # Allow up to 10s for a response

scrape_configs:
  # Scrape Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090'] # Use the service name

  # Scrape the backend
  - job_name: 'backend'
    static_configs:
      - targets: ['backend:3003'] # Use the service name
    metrics_path: '/api/metrics'
